---
- name: renovate/container
  color: "027fa0"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
- name: hold
  color: "ee0701"
- name: app/lidarr
  color: 0e8a16
- name: app/lidarr-plugins
  color: 0e8a16
- name: app/nsxlibrarymanager
  color: 0e8a16
- name: app/wyoming-glados
  color: 0e8a16
